import type { Campaign, Client, ContentItem, GenerationJob } from "@/lib/domain";

export const demoClient: Client = {
  id: "client-sunrise-clean",
  organizationId: "org-estrategiapro",
  companyName: "Sunrise Clean Co.",
  industry: "Limpeza residencial e comercial",
  service: "Limpeza recorrente, pós-obra e mudança na Grande Boston",
  region: "Malden, MA · Grande Boston",
  contactName: "Mariana Costa",
  contactEmail: "mariana@sunriseclean.co",
  instagram: "@sunriseclean.co",
  website: "sunriseclean.co",
  marketingMaturity: "Marketing ativo, com necessidade de consistência",
  differentiators: [
    "Equipe segurada e treinada",
    "Orçamento em até 15 minutos",
    "Atendimento em inglês, português e espanhol",
  ],
  active: true,
  brandKit: {
    id: "brand-sunrise-clean",
    clientId: "client-sunrise-clean",
    palette: {
      primary: "#124E66",
      secondary: "#2E8BC0",
      accent: "#F6AE2D",
      background: "#F7FBFD",
      text: "#12212A",
    },
    visualStyle: "current",
    toneOfVoice: "Acolhedor, confiável e objetivo. Linguagem simples, profissional e próxima das famílias locais.",
    requiredTerms: ["insured", "trusted", "free estimate"],
    forbiddenTerms: ["cheap", "guaranteed perfection"],
    preferredCta: "Peça seu orçamento gratuito pelo WhatsApp.",
    imageReferences: [],
  },
  contract: {
    id: "contract-growth-2026",
    clientId: "client-sunrise-clean",
    name: "Plano Crescimento · Social + Vídeo",
    status: "active",
    startsAt: "2026-07-01",
    endsAt: "2026-12-31",
    market: "US",
    timezone: "America/New_York",
    generationCadence: "weekly",
    nextGenerationAt: "2026-08-02T23:00:00-04:00",
    approvalRequired: true,
    deliveryRules: [
      { id: "rule-1", channel: "instagram", format: "photo", quantity: 2, period: "week", objective: "attract" },
      { id: "rule-2", channel: "instagram", format: "reel", quantity: 1, period: "week", objective: "convert" },
      { id: "rule-3", channel: "google_business", format: "photo", quantity: 1, period: "week", objective: "attract" },
      { id: "rule-4", channel: "instagram", format: "carousel", quantity: 2, period: "month", objective: "educate" },
    ],
    specialDateRules: [
      {
        id: "holiday-1",
        eventKey: "labor_day",
        label: "Labor Day",
        eventDate: "2026-09-07",
        quantity: 1,
        format: "photo",
        isExtra: true,
        enabled: true,
      },
      {
        id: "holiday-2",
        eventKey: "thanksgiving",
        label: "Thanksgiving",
        eventDate: "2026-11-26",
        quantity: 2,
        format: "reel",
        isExtra: false,
        enabled: true,
      },
    ],
  },
};

export const demoCampaign: Campaign = {
  id: "campaign-august-week-1",
  clientId: demoClient.id,
  contractId: demoClient.contract.id,
  name: "Semana de Recomeços · Agosto",
  goal: "Gerar pedidos de orçamento para limpeza pós-mudança e recorrente.",
  startsAt: "2026-08-03",
  endsAt: "2026-08-09",
  status: "in_review",
  createdAt: "2026-08-02T23:10:00-04:00",
};

export const demoContent: ContentItem[] = [
  {
    id: "content-1",
    campaignId: demoCampaign.id,
    clientId: demoClient.id,
    title: "Volte à rotina com a casa em ordem",
    scheduledAt: "2026-08-03T09:00:00-04:00",
    channel: "instagram",
    format: "photo",
    objective: "attract",
    pillar: "Rotina e bem-estar",
    status: "review",
    caption: "A semana fica mais leve quando a casa começa limpa. Nossa equipe cuida dos detalhes para você recuperar seu tempo e sua tranquilidade.\n\nAtendemos Malden e a Grande Boston com equipes seguradas e orçamento rápido.\n\nPeça seu orçamento gratuito pelo WhatsApp.",
    hashtags: ["#BostonCleaning", "#MaldenMA", "#HouseCleaning", "#CleanHome"],
    creativeBrief: "Foto com luz natural de uma sala organizada, pessoa adulta colocando flores em uma mesa clara. Aplicar detalhes visuais em azul-petróleo e amarelo da marca de forma discreta.",
    imagePrompt: "Bright and welcoming clean living room in Greater Boston home, natural morning light, elegant navy blue and warm yellow accents, authentic lifestyle photography, no visible text, premium home cleaning brand style.",
    generatedByAi: true,
  },
  {
    id: "content-2",
    campaignId: demoCampaign.id,
    clientId: demoClient.id,
    title: "3 sinais de que sua limpeza pós-mudança precisa de profissionais",
    scheduledAt: "2026-08-05T12:00:00-04:00",
    channel: "instagram",
    format: "carousel",
    objective: "educate",
    pillar: "Autoridade",
    status: "review",
    caption: "Mudança concluída, mas a casa ainda não parece pronta? Estes três sinais indicam que uma limpeza pós-mudança profissional pode fazer toda a diferença.\n\nDeslize para ver e salve este post para o seu próximo endereço.",
    hashtags: ["#MoveOutCleaning", "#BostonMove", "#CleaningTips", "#MaldenBusiness"],
    creativeBrief: "Carrossel de cinco slides. Capa com pergunta curta; três slides com sinais; último slide com CTA. Visual atual, muito espaço em branco, ícones simples e paleta da marca.",
    imagePrompt: "Modern editorial social media carousel visual, clean home, navy and warm yellow branded accent palette, generous whitespace, premium local cleaning service, no text.",
    generatedByAi: true,
  },
  {
    id: "content-3",
    campaignId: demoCampaign.id,
    clientId: demoClient.id,
    title: "Uma limpeza profissional em 30 segundos",
    scheduledAt: "2026-08-07T18:30:00-04:00",
    channel: "instagram",
    format: "reel",
    objective: "convert",
    pillar: "Bastidores",
    status: "review",
    caption: "O que muda quando uma equipe treinada cuida da sua casa? Veja a transformação e imagine como seria chegar em casa sem uma lista de limpeza esperando por você.\n\nPeça seu orçamento gratuito pelo WhatsApp.",
    hashtags: ["#CleaningReel", "#BostonHomes", "#BeforeAndAfter", "#HouseCleaningService"],
    creativeBrief: "Vídeo vertical de até 30 segundos, cortes curtos de antes/depois, detalhes de superfície limpa e final com ambiente acolhedor. Sem promessas absolutas ou texto sobreposto excessivo.",
    videoScript: "0–3s: Gancho — ‘Sua semana não deveria começar com uma lista de limpeza.’\n4–18s: Mostrar equipe preparando materiais, detalhe de bancada, sala finalizada e banheiro brilhante.\n19–25s: ‘Equipes seguradas e treinamento para cuidar do seu espaço.’\n26–30s: CTA na tela e locução — ‘Peça seu orçamento gratuito hoje.’",
    generatedByAi: true,
  },
  {
    id: "content-4",
    campaignId: demoCampaign.id,
    clientId: demoClient.id,
    title: "Oferta local para primeira limpeza recorrente",
    scheduledAt: "2026-08-08T10:00:00-04:00",
    channel: "google_business",
    format: "photo",
    objective: "convert",
    pillar: "Promoção",
    status: "planned",
    caption: "Comece sua rotina de limpeza com uma equipe confiável na Grande Boston. Solicite seu orçamento gratuito e conheça as opções de limpeza recorrente para sua casa ou escritório.",
    hashtags: [],
    creativeBrief: "Imagem quadrada de equipe sorridente em entrada residencial, uniforme azul discreto, sensação de confiança e proximidade local.",
    imagePrompt: "Professional insured home cleaning team at a Greater Boston residence entrance, trustworthy warm smile, clean navy uniforms, bright natural light, premium local service photography, no text.",
    generatedByAi: true,
  },
];

export const demoJobs: GenerationJob[] = [
  {
    id: "job-1",
    clientId: demoClient.id,
    campaignId: demoCampaign.id,
    type: "content_batch",
    status: "completed",
    scheduledFor: "2026-08-02T23:00:00-04:00",
    attempts: 1,
    maxAttempts: 3,
  },
  {
    id: "job-2",
    clientId: demoClient.id,
    type: "campaign_plan",
    status: "queued",
    scheduledFor: "2026-08-09T23:00:00-04:00",
    attempts: 0,
    maxAttempts: 3,
  },
];
